name: Tests

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/checkout@v2
    -  name: Install PHP
       uses: shivammathur/setup-php@v2
       with:
        php-version: 8.1
    - name: Copy .env file
      run: |
        cp .env.ci .env
    - name: Run Composer
      run: |
        composer install --no-interaction
    - name: Run test suite
      run: | 
        php artisan test   
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.leadit.ar
        username: rodri@leadit.ar
        password: MolotoV555
        server-dir: /laravel/